optim:
    lr: 0.0004
    betas: [0.9, 0.999]
    weight_decay: 0

data:
    partition_path: "config/data/musdb18hq.yaml"
    segment: 11
    stride: 1
    stems: ["drums", "bass", "vocals"]

inference:
    overlap: 0.2
    max_parallel_windows: null

train:
    loss_weights: [1, 1, 1, 1]

model:
    sources: ${data.stems}
    audio_channels: ${data.channels}
    dims: [4, 32, 64, 128]
    stft_config:
        n_fft: 4096
        hop_length: 1024
        win_length: 4096
        normalized: True
    band_config:
        low:
            SR: 0.175
            stride: 1
            kernel: 3
        mid:
            SR: 0.392
            stride: 4
            kernel: 4
        high:
            SR: 0.433
            stride: 16
            kernel: 16
    conv_depths: [3, 2, 1]
    conv_config:
        compress: 4
        kernel: 3
    num_dplayer: 6
    expand: 1

augment:
    shift_same: False
    remix:
        proba: 1
        group_size: 4
    scale:
        proba: 1
        min: 0.25
        max: 1.25
    flip: True